name: $(Rev:r)
trigger:
- master
- refs/tags/*
jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: dotnet test build.proj
    displayName: dotnet test
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: 'tests/**/*.trx'
    condition: succeededOrFailed()
  - script: dotnet pack build.proj
    displayName: dotnet pack
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: echo "##vso[task.setvariable variable=FrameworkPathOverride]$(dirname $(which mono))/../lib/mono/4.5/"
    displayName: Workaround .NET reference assemblies on linux
  - script: dotnet test build.proj
    displayName: dotnet test
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: 'tests/**/*.trx'
    condition: succeededOrFailed()
  - script: dotnet pack build.proj
    displayName: dotnet pack build.proj
    env:
      BUILD_PR: $(SYSTEM.PULLREQUEST.PULLREQUESTNUMBER)
      BUILD_ID: $(BUILD.BUILDNUMBER) 
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'bin'
      artifactName: 'nupkgs'
  - task: NuGetCommand@2
    condition: succeededOrFailed()
    inputs:
      command: push
      nuGetFeedType: external
      publishFeedCredentials: 'Jet-MyGet'
      versioningScheme: byEnvVar
      versionEnvVar: Version
      packagesToPush: 'bin/*.nupkg;bin/*.symbols.nupkg'
- job: MacOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: echo "##vso[task.setvariable variable=FrameworkPathOverride]$(dirname $(which mono))/../lib/mono/4.5/"
    displayName: Workaround .NET reference assemblies on linux
  - script: dotnet test build.proj
    displayName: dotnet test
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: 'tests/**/*.trx'
    condition: succeededOrFailed()
  - script: dotnet pack build.proj
    displayName: dotnet pack